server:
  port: 8060
  host: http://localhost:8060/

spring:
  datasource:
    driver-class-name=: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/short_url?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: password

  redis:
    host: localhost
    port: 6379
    connect-timeout: 10000ms

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
